### ISSUE TITLE
/:service/:method HTTP endpoint

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#1]
As a developer I want to expose public methods on annotated Java classes of my backend app to the frontend, so that they can be invoked via the `/:service/:method` HTTP endpoint.

DoD:
 - there is a new `@VaadinService` annotation with the `RUNTIME` retention policy
 - the annotation allows specifying the service name (optionally). The default name is the simple name of the Java class (Literally)
 - at the application startup the class path is scanned to find all classes with the `@VaadinService` annotation, and all public methods on these classes are identified
 - there is an HTTP request handler on the `/:service/:method` URL that
   - maps HTTP POST requests to the identified classes / methods
   - deserializes call parameters
   - obtains an instance of the service class
   - calls the matching method
   - serializes the return value and creates an HTTP response from it
 - method parameters are deserialized from the request body (assuming JSON payload and using Jackson)
 - an instance of the matching Vaadin Service class is obtained from the application context (for this ticket it's enough to support only Spring apps)
 - the return value is serialized into JSON using Jackson and returned in the response body
 - any serializable types are supported for of method parameters and return values

The [common DoD](https://github.com/vaadin/vaadin-services/wiki/Definition-of-Done) applies.

**Comment by Legioth** [comment]
Recommended to use the pre-configured Jackson setup provided by Spring through `Jackson2ObjectMapperBuilder`. The benefit of this is that it's automatically configured to use some common Jackson add-ons such as support for Java 8 date types.
