### ISSUE TITLE
add a 'withCredentials' option to the Connect Client 'call' method

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#100]
When calling a backend method with `ConnectClient` I want the `call` method to have an option to skip calling the `credentials` provider if the access token is missing so that I can call 'public' methods on the backend without forcing users to login.

DoD:
 - the `call` method accepts an optional 4th argument for an options object
 - there is a `withCredentials` boolean option with a default value of `true`
 - when the `withCredentials` option is `false` Connect Client does not trigger the `credentials` provider if the access token is missing
 - when the `withCredentials` option is `false` but Connect Client does have an access token at the time of the call, it does include the access token with the request

**Comment by vlukashov** [comment]
> > when the `withCredentials` option is false Connect Client does not include the access token into the request
> 
> Would it be more useful if the access token would be included if one is available? In that way, the same endpoint can still choose to e.g. include extra details for logged in users while still providing basic access to logged out users.

Suggestion accepted. Thanks!

**Comment by platosha** [comment]
Would it be more appropriate to call it `requireCredentials` then?
