### ISSUE TITLE
Cover VaadinConnectController with unit tests

### ISSUE THREAD

**Issue by SomeoneToIgnore** [vaadin/vaadin-connect#112]
`com.vaadin.connect.VaadinConnectController` class lacks unit tests and excluded from the jacoco coverage checks to allow to proceed with the coverage level agreed.

Even though there are IT tests in `vaadin-connect-demo` that verify the class functionality, those are hard to append to jacoco reports via pom.xml configuration and are slow to run.

Hence we need to write enough unit tests on the class in `vaadin-connect` module so the tests are run as fast as possible and are easy to include into jacoco report.
After that, we need to remove the https://github.com/vaadin/vaadin-connect/pull/111/files#diff-600376dffeb79835ede4a0b285078036R184 TODO in the main pom.xml and verify that the coverage level is met.

**Comment by vlukashov** [comment]
using a Spring Test context is OK
