### ISSUE TITLE
Improve the OpenAPI generator with JavaSymbolResolver

### ISSUE THREAD

**Issue by qtdzz** [vaadin/vaadin-connect#113]
The current Java parser can't resolve the actual information of the parsed node. For example, we can just get the return type of a method but it doesn't contain the actual information of the type e.g. full qualified name, ancestor, ...
By setting up the configuration with JavaSymbolResolver (e.g. https://github.com/vaadin/vaadin-connect/commit/43ee0e7b4f6a00c6f668ea8b8439f06e1fd2815c), the Java parser could resolve the parsed types, then we can the full qualified name and ancestors . This would be helpful for better types mapping and schemas creating.

**Comment by vlukashov** [comment]
- remove the hardcoded list of collection classes and check if a type implements a white list of collection interfaces instead
 - fix 6. All super class methods are missing from the JS generated for my `@VaadinService`
