### ISSUE TITLE
define JS -> Java type conversion rules

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#115]
When passing a JS value into a Java method on the backend via Vaadin Connect I want to know exactly the value / type coercion rules applied by the Vaadin Connect so that I can build a robust app and know its behavior in all corner cases.

DoD:
 - there is a docs page describing the default JS -> Java value / type coercion rules
 - there are unit tests covering all rules (both FE and BE)
 - the types in scope:
   - all primitives (e.g. `int`)
   - all boxed primitives (e.g. `java.lang.Integer`)
   - `java.lang.String`
   - date / time types
   - JSON objects
   - arrays
   - collections
   - enums
   - maps with string / enum keys
   - beans
 - same tests and docs for the Java -> JS conversion
 - create a list of what needs to change so that type conversion rules make most sense (e.g. what to do with Java long -> JS, date / times both ways, etc)

**Comment by SomeoneToIgnore** [comment]
Reopened, since 

> same tests and docs for the Java -> JS conversion

is not done in https://github.com/vaadin/vaadin-connect/pull/157 , agreed in the same PR that this point will be implemented later.

What's missing is the documentation page on Java -> JS conversion and corner cases like Java Long.MAX_VALUE -> JS conversion
