### ISSUE TITLE
Vaadin Client should automatically use a refresh token if the access token expires

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#12]
When using the Vaadin Services JS client, I want it to automatically use a refresh token if the backend response indicates that the provided access token has expired, so that the default configuration of a Vaadin Serivces project automatically allows users to stay logged-in longer than the expiration period of a single access token.

DoD:
 - Vaadin Client has an `refreshToken` property
 - the `refreshToken` is persisted into the local storage on every update and is read from there when the client is initialized
 - when Vaadin Client gets an 'unauthorized' error in response to a call that included an access token, and when `refreshToken` is defined, Vaadin Client [gets a new pair of access and refresh tokens from the authorization server](https://github.com/vaadin/vaadin-services/issues/6) and repeats the original request with the new access token
 - if `refreshToken` is not defined or if the refresh request fails, Vaadin Client [prompts the user for password credentials](https://github.com/vaadin/vaadin-services/issues/11)

Implementation note:
The behavior of using a refresh token to obtain a new access token in cases when  no valid access token is available should be implemented in a way that's possible to override in the future. Preferably, as a middleware for the Vaadin Client class (a middleware that provides an access token when called).

The [common DoD](https://github.com/vaadin/vaadin-services/wiki/Definition-of-Done) applies.

**Comment by Legioth** [comment]
Could also consider whether a new access token should proactively be requested once the access token expires so that there won't be the need to do two separate round trips when the user actually wants to do something.

To avoid draining the battery of a user device, we should only do proactive token refreshing when the browser tab is active.

**Comment by vlukashov** [comment]
Proactive access token refreshing is a separate task: https://github.com/vaadin/vaadin-services/issues/14
