### ISSUE TITLE
role-based ACL on the backend Vaadin Service methods

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#13]
When defining Java methods that are exposed on a Vaadin Service class, I want to use annotations to define the required roles either on the class level or on the method level so that security rules are declarative and are easy to read and write.

DoD:
 - it should be possible to annotate Vaadin Service classes and / or individual methods with a list of required roles
 - when a Vaadin Service method call is handled on the backed, the access token connected with that call is checked against the list of required roles. If the check does not pass, the method is not executed and an auth error is returned to the client.
 - the standard `javax.annotation.security` annotations should be supported: `@RolesAllowed`, `@DenyAll`, `@PermitAll`
   - `@PermitAll` allows access to all _authenticated_ users (i.e. anonymous users still would not have access to that method)
   - `@RolesAllowed` allows access to users that have at least one of the listed roles
   - `@DenyAll` prohibits access to all users
 - the default behavior (if no annotation is present) is equivalent to `@PermitAll`, i.e. by default Vaadin Serivce mehods are accessible to all logged in users

The [common DoD](https://github.com/vaadin/vaadin-services/wiki/Definition-of-Done) applies.

**Comment by Legioth** [comment]
Should also be defined how handle cases when no annotation is present. There's three potential approaches to take in that case:
* Always allow access for any request
* Allow access for logged in users, but reject for anonymous users
* Always reject access for any request

I'm leaning towards the most strict alternative in the name of having safe defaults, but I can also see how it would be convenient to by default allow access for logged in users. Accepting any request is out of the question IMHO.

**Comment by vlukashov** [comment]
I've updated the ticket description. The default is to allow access to _authenticated_ users.
