### ISSUE TITLE
remove the 'empty operationId' warning

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#135]
Address the following feedback:
> 8. I get many `[WARNING] Empty operationId found for path: ...` on each Java change. Not sure why I should care about an `operationId` or what it even is

# Steps to reproduce
 - get the base starter
 - run `./mvnw package`
 - see the warning in the build output:
   ```
   [INFO] --- vaadin-connect-maven-plugin:0.1.1:generate-connect-modules (vaadin-connect-resources) @ base-starter-connect ---
   [INFO] No .swagger-codegen-ignore file found.
   [WARNING] Empty operationId found for path: post /GreeterService/greet. Renamed to auto-generated operationId: greeterServiceGreetPost
   [INFO] writing file /Users/viktor/IdeaProjects/vaadin-services/starter-demo/frontend/src/generated/GreeterService.js
   ```

# Expected outcome
As long as the Java classes annotated with `@VaadinService` have no issues, there should not be warnings during the build. So, no warning is expected in this case.

**Comment by qtdzz** [comment]
It should be fixed in this  commit https://github.com/vaadin/vaadin-connect/pull/118/commits/12cca3768984a7ef06943e937516f9638ced3025
