### ISSUE TITLE
A service method cannot be named 'delete'

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-connect#145]
In a CRUD endpoint it's quite logical to have a 
```
public void delete(long id) {
``` 
method. This will cause invalid JS to be generated:
```
export const delete = service.delete.bind(service);
```
and finally cause "Uncaught SyntaxError: Unexpected token delete"

**Comment by vlukashov** [comment]
Expected behavior: Build failure with a descriptive error message pointing to the line in the Java source file where the `delete` keyword is used.
