### ISSUE TITLE
LocalDate is not converted using Spring Boot default

### ISSUE THREAD

**Issue by Artur-** [vaadin/vaadin-connect#153]
The Spring Boot default for encoding of a `LocalDate` is to convert it to ISO format, e.g `2018-12-13`. Thus if you do 
```
@RestController
public class FooRestController {

    @GetMapping("/foo")
    public LocalDate foo() {
        return LocalDate.now();
    }
}
```

then http://localhost:8080/foo/ will return `"2018-12-17"`

However, if you do 
```
@VaadinService
public class MyService {
    public LocalDate foo() {
        return LocalDate.now();
    }
}
```
then the return value is `[2018,12,17]`

The reason seems to be that the `VaadinConnectController` constructor
```
    this.vaadinServiceMapper = vaadinServiceMapper != null ? vaadinServiceMapper
        : Jackson2ObjectMapperBuilder.json()
            .visibility(PropertyAccessor.ALL, JsonAutoDetect.Visibility.ANY)
            .build();
```

`Jackson2ObjectMapperBuilder.json()` will create a new instance of `Jackson2ObjectMapperBuilder` instead of using the preconfigured one constructed in `JacksonAutoConfiguration` in Spring Boot.

**Comment by vlukashov** [comment]
This is fixed by using the Spring Boot defaults for the Jackson JSON `ObjectMapper` config (https://github.com/vaadin/vaadin-connect/pull/157).
