### ISSUE TITLE
allow overriding the default Vaadin Client config

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#163]
When setting a custom credentials provider for the default Connect Client, I want to do that straight in the file that configures and exports the default Vaadin Connect client instance for the app, so that my modifications apply to all default service instances in the app regardless of the order they are created.

Currently the default Vaadin Connect client module is generated in `generated/connect-client.default.js`. Modifying the generated file is not acceptable because either all changes are gone after the next build that regenerates the file, or the assumption that the `generated/` folder can safely be deleted at any time is broken. Thus, **it should be possible to create a custom `vaadin-client.js` file outside of the `generated/` folder**.

It should still be possible to build and run a project without a hand-written `connect-client.js` file to follow the _"make simple things easy"_ vision. Thus, a default client module should still be generated if no custom one is provided. The generated file has to reside inside the `generated/` folder.

The JS wrappers generator needs to know the path to the default Vaadin Connect client module at the build time (because all generated wrappers need to import and use it). If that path is no longer fixed as `generated/connect-client.default.js`, the generator needs some way to know what the path is.

DoD:
 - introduce a convention: if there is a file named `connect-client.js` in the `frontend/src/` folder, that file is used as the default Vaadin Connect client module
 - add a property into `application.properties` that allows explicitly setting the path to the default Vaadin Connect client module file (if specified it overrides the conventional file name)
 - when running the JS generator, the default client file is generated only if there is no custom one (the default generated client module file is removed if a custom client module file is present)
 - document the rules of selecting the default Connect client for an app
 - update the starter to use a custom connect client (with vaadin login component)

**Comment by Legioth** [comment]
Couldn't this be achieved in an easier way by making it possible to configure an existing client instance on the fly (and thus also look up any configuration settings as late as possible).

In that way, one could simply import the default client instance, modify its configuration and any calls made after that would use the new settings. This would typically be done in e.g. `app.js` that also sets up e.g. the router.

**Comment by vlukashov** [comment]
> Couldn't this be achieved in an easier way by making it possible to configure an existing client instance on the fly (and thus also look up any configuration settings as late as possible).
> 
> In that way, one could simply import the default client instance, modify its configuration and any calls made after that would use the new settings. This would typically be done in e.g. `app.js` that also sets up e.g. the router.

That would be a simpler approach, and that's the one I've tried first before coming with the suggestion above. The reason why the simple approach does not always work is that it requires a strong guarantee that the client is never used before it is initialized. There are cases when ensuring it is not so straightforward:

`index.html`
```html
<vaadin-grid></vaadin-grid>
<script type="module" src="index.js"></script>
```

`index.js`
```javascript
import client from './src/generated/connect-client.default.js';
client.credentials = ...; // configure the default client

import './src/my-vaadin-grid-config.js';
```

`my-vaadin-grid-config.js`
```javascript
import '@vaadin/vaadin-grid/vaadin-grid.js';
import {getVaadinGridData} from './generated/GridDataService.js';

const grid = document.querySelector('#grid');
grid.size = 1000;
grid.dataProvider = function (params, callback) {
  getVaadinGridData(params.page, params.pageSize, []).then(data => {
    callback(data);
  });
};
```

In this case the grid web component gets upgraded before the code in the `index.js` module gets a chance to run, and the client is used before it is configured. Sure we could write in the docs that client configuration has to be done in a synchronous script before importing any modules and configuring any web components, but I am not convinced that it relying on the docs in this regards is worth it.
