### ISSUE TITLE
support passing List<MyBean> from JS to Java

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#175]
When creating Vaadin Connect service methods in Java I want the `` type of parameters to be supported so that I can accept lists of custom beans from JS.

Currently this does not work with `500 (Internal Server Error)`:

```java
@VaadinService
public class MyService {
    public static class Filter {
        private String path;
        private String value;

        public Filter() {
        }

        public String getPath() {
            return path;
        }

        public void setPath(String path) {
            this.path = path;
        }

        public String getValue() {
            return value;
        }

        public void setValue(String value) {
            this.value = value;
        }
    }

    public String getTypeOfBeanInTheList(List<Filter> filters) {
        return filters.get(0).getClass().getSimpleName();
    }
}
```

```javascript
myService.getTypeOfBeanInTheList([{path: 'a.path', value: 'some value'}])
```

This seems to be a deserializer issue because the type of the parameter passed into the server side method is:
![image](https://user-images.githubusercontent.com/22416150/50345442-c2242680-0537-11e9-8f0f-e631c728221c.png)

**Comment by Legioth** [comment]
The same probably also applies for e.g. `Set<Filter>` and `Map<String, Filter>`? Or would those be separate issues?

A good question here is exactly which declared types to support. Is it only `java.util.List`, or also e.g. `java.util.ArrayList` and `java.util.LinkedList` (and correspondingly for `Set` and `Map` types)?

**Comment by vlukashov** [comment]
This is fixed by using the Spring Boot defaults for the Jackson JSON `ObjectMapper` config (https://github.com/vaadin/vaadin-connect/pull/157).

This also applies to Set, Map, etc.
