### ISSUE TITLE
create a basic Vaadin Frontend Server controller

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#176]
When starting a Vaadin app built for production I want it to serve the `index.html` file for all requests that do not match a static file so that I can build a single-page app with HTML5 in-browser routing and reloading a page there does not lead to a 404.

DoD:
 - there is a new maven module in the vaadin-connect repo: `vaadin-frontend-server` (note no `connect` in the name - potentially it could be used standalone at some point)
 - there is a `VaadinFrontendServerController` class that handles all HTTP requests that are neither for the Vaadin Connect OAuth endpoint, nor to the Vaadin Connect RPC endpoint
 - each HTTP request that matches a pattern for static files is handled in the same way as the default Tomcat static file handler would do it (either returning the file as is, or returning a 404 if there is no file with that name)
 - the default pattern for static files is _"any file that has an extension, and the extension is one of {.html, .js, .css, .json, .png, .jpg, .ico, .svg, .woff, .woff2, .ttf}"_
 - for each HTTP request that does not match the pattern for static files the server returns the `index.html` file from the web application context
 - `VaadinFrontendServerController` is enabled automatically when the `vaadin-frontend-server` dependency is added to the app
 - the base starter is updated to use the frontend server
 - no integration tests yet
 - there is a documentation page describing `VaadinFrontendServerController`: what it is, why and when to use it, how to use it

child of #170

**Comment by SomeoneToIgnore** [comment]
Need to adjust Vaadin Connect release job to deploy this module's artifact also.
