### ISSUE TITLE
make the Vaadin Frontend server configurable

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#178]
When using the Vaadin Frontend server I want to configure the dynamic routes pattern so that I can define which URLs are handled by the SPA and which ones are static.

<details>
  <summary>Two alternative approaches to configuration API</summary>

 - parameters in the `@EnableVaadinFrontendServer` annotation
   ```java
   @EnableVaadinFrontendServer(
     singlePageTemplate = "index.html"
     staticContentPattern = "*.html|.js|*.css|*.json|*.png|*.jpg|*.ico|*.svg|*.woff|*.woff2|*.ttf")
   public class DemoApplication {
   }
   ```
   This is less flexible (only primitive values allowed for configuration), but not Spring-dependent

 - the configurer pattern (widely used in Spring: [ServerCodecConfigurer](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/codec/ServerCodecConfigurer.html), [AsyncConfigurer](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/scheduling/annotation/AsyncConfigurer.html) or [WebSecurityConfigurer](https://docs.spring.io/spring-security/site/docs/current/api/org/springframework/security/config/annotation/web/WebSecurityConfigurer.html))
   ```java
   @Configuration
   public class MyFrontendConfiguration implements VaadinFrontendServerConfigurer {

     @Override
     public void configure(VaadinFrontendServerConfigurationBuilder frontend) {
       frontend
         .singlePage("index.html")
         .and()
         .staticContent("/")
           .includeMatching("**/*.html")
           .includeMatching("**/*.css")
           .includeMatching("**/*.js");
     }
   }
   ```
   or
   ```java
   @Configuration
   public class MyFrontendConfiguration implements VaadinFrontendServerConfigurer {
   
     @Override
     public String singlePageTemplatePath() {
       return "index.html";
     }
   
     @Override
     public String staticContentPattern() {
       return "*.html|.js|*.css|*.json|*.png|*.jpg|*.ico|*.svg|*.woff|*.woff2|*.ttf";
     }
   }
   ```
   This is more flexible, but depends on Spring for IoC features.

The Vaadin Connect Auth server already uses the 2nd approach for configuration. Thus, the Vaadin Frontend server config should use that as well for consistency. When a version of Vaadin Connect without Spring dependency becomes required, the way to remove it could be that a configurer class would be a required property in the `@EnableVaadinFrontendServer`  / `@EnableVaadinConnectOAuthServer` annotations: 
```java
@EnableVaadinFrontendServer(MyFrontendConfiguration.class)
public class MyApp {
}
```
</details>

⁠
DoD:
 - there is a `VaadinFrontendServerConfigurer` interface that allows to override the default value for
   - the pattern for dynamic routes (e.g. via a `String dynamicRoutesPattern()` method)
 - in a Spring app when the Vaadin Frontend server is enabled, the context is scanned for classes implementing the `VaadinFrontendServerConfigurer` interface
 - if there are several implementations, there is a run time error and the application start fails with a descriptive error message (see [AbstractAsyncConfiguration.setConfigurers()](https://github.com/spring-projects/spring-framework/blob/master/spring-context/src/main/java/org/springframework/scheduling/annotation/AbstractAsyncConfiguration.java#L69) for an example)
 - if there are no implementations, the default values are used
 - if there is exactly one implementation, the values from that configurer are used
 - the docs page is updated to tell how to customize the defaults

child of #170

**Comment by manolo** [comment]
In the PR we removed the welcomeFile configuration since it can be easily customised in the servlet container, as well as changed included and excluded mappings with a route matcher interface that the user can provide in the spring context
