### ISSUE TITLE
dev mode compatible with the Frontend server config

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#185]
When running / debugging an app in the dev mode I want have the same SPA / frontend server config as in production when using the Frontend server so that I am confident that if the app runs in dev, it runs the same way in production as well.

DoD:
 - Vaadin Frontend server config for production applies when in dev mode:
   - index.html
   - static resources pattern
   - base URL rewrite

Requires research. Timebox 1 day.

child of #170

**Comment by manolo** [comment]
There are different options:

- Adapt frontend server to check whether the webpack-middleware returns a not found and then proxy to backend. This needs and additional proxy to the webpack server and inspect every request response code.
  - pros: the current approach is still re-usable, no need to change docs, etc.
  - cons: probably we need to add some new npm deps, and add some complexity to frontend.js

- Make the backend server the final endpoint, so as java has a proxy to request all the static stuf to the webpack-server.
  - pros: final user always uses one port in prod and dev (8080) (artur already mentioned this). We can remove proxy code from frontend.js
  - cons: need to introduce new java deps (proxy library), and deal with devmode detection to replace spring static handler by a custom handler using the proxy. More complexity in java side.

- Get rid of frontend.js and make spring-boot serve static compiled stuff. We still need to run webpack in watch mode to detect changes and output stuff in the resources folder.
  - pros: we can remove frontend.js amd some of its npm deps. We remove setup complexity by avoiding a frontend server. Less confusion for devs (especially java) and more aligned with Flow. Easier setup
  - cons: need to adapt docs. Browser automatic reloading when changing static files might not work (can still be performed)


I have evaluated the three options, and the most feasible and eaiest is the last one, in fact I have prototyped that in this [branch](https://github.com/vaadin/vaadin-connect/commit/ee1406cdd1e3abf49960e5092dd743328e35b8ad) and everything works without breaking tests.
In addition, I have tested the embedded [livereload](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-devtools.html#using-boot-devtools-livereload) feature of spring-boot, and it works as a charm. Hence web developers only need to install an extension in their browsers and any single change in static or java code fires a browser reload.

**Comment by manolo** [comment]
Video with livereload in action in my branch https://youtu.be/ZJjeIfItcDs

**Comment by manolo** [comment]
As discussed in https://vaadin.slack.com/archives/CDNTYMS9H/p1547197861029300 we will implement option 3 (#228) and bring back the webpack-dev-server when appropriate (#229)
