### ISSUE TITLE
watch Java source changes and regenerate the OpenAPI spec

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#19]
When generating [per-service ES modules](https://github.com/vaadin/vaadin-services/issues/3) I want to have the [OpenAPI v3 spec file](https://github.com/vaadin/vaadin-services/issues/18) automatically updated every time when the relevant parts of the project sources change so that the ES modules can be automatically kept in sync with the Java sources and I can have a seamless 'hot reload' experience.

DoD:
 - there is an executable Java class that starts a file system watcher on the Java sources of a given project and triggers the [OpenAPI spec generator](https://github.com/vaadin/vaadin-services/issues/18) every time when relevant sources get updated.
 - there is a documentation page (.asciidoc) that describes what the does this watcher do and what options does it have. The aim is that this documentation page will be converted into the [vaadin-connect-maven-plugin](https://github.com/vaadin/vaadin-services/issues/22) docs page when the plugin is created. Therefore the focus should be put on the parts of the docs that would be applicable to the maven plugin.

Implementation note: watching file system changes can be done with the [directory-watcher](https://github.com/gmethvin/directory-watcher) library.

The [common DoD](https://github.com/vaadin/vaadin-services/wiki/Definition-of-Done) applies.

child of #3

**Comment by qtdzz** [comment]
At this point, I assume that we already have the maven plugin at this time, so instead of an executable Java class, let's make it as a new task in the maven plugin.
