### ISSUE TITLE
server-side API to trigger client-side validation errors

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#194]
When handling a Vaadin Connect service method call I want to throw an exception that triggers a client-side `ValidationError` so that I can implement custom server-side validation rules and have the same-looking validation errors on the client as the ones from built-in validation rules.

depends on #173 
depends on #202 

DoD:
 - there is a `ValidationException` Java exception class ([propagated](https://github.com/vaadin/vaadin-connect/issues/173) to the Connect client)
 - `ValidationException` includes a list of validation errors, that each have 2 properties:
   - parameter name (optional, can be a path like `user.address.zipcode`)
   - message (required)
 - at least one validation error is required to create a `ValidationException`
 - when a Vaadin Connect service method throws a `ValidationException`, the call promise in the client side is rejected with a `ValidationError` that contains the list of errors provided by the backend
 - the mapping from `VaadinServiceException`s into `ValidationException` is done as a [ConnectClient middleware](https://github.com/vaadin/vaadin-connect/issues/202) that is added in the default `ConnectClient` config
 - there is a documentation page describing how to use the API

child of #169

**Comment by Legioth** [comment]
What about reporting multiple validation errors for the same method call? Would it make sense for `ValidationException` to instead contain a list of beans that each contains a required parameter name and an optional message?

**Comment by vlukashov** [comment]
Multiple errors in a single exception - yes. There is a plan to support it eventually, so it makes sense to build the API with that in mind. I've updated the issue description.

_Required_ parameter name - seems like a no, because that does not really apply to cross-field validation errors.
