### ISSUE TITLE
release Vaadin Connect

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#212]
When evaluating / DX testing Vaadin Connect, I want to do that against a specific version of the core library and the starter project, so that the findings I report are easy to reproduce.

See the [release checklist](https://docs.google.com/spreadsheets/d/13E1G20zgEb5PiBQH9-diPS0a8CDn5NrnfrruZegxJ0M/edit#gid=0)

DoD:
 - the `com.vaadin:vaadin-connect:0.4.0` dependency can be installed from the `maven.vaadin.com/vaadin-prereleases` repo
 - both sources and javadoc for `com.vaadin:vaadin-connect` are available on  `maven.vaadin.com/vaadin-prereleases` as well
 - the demo app is not included into the `com.vaadin:vaadin-connect` dependency. Only the core library
 - the `com.vaadin:vaadin-connect-maven-plugin:0.4.0` dependency can be installed from  the `maven.vaadin.com/vaadin-prereleases` repo
 - the `@vaadin/connect#0.4.0` package can be installed from npm
 - there is a `0.4.0` GitHub release (and a `v0.4.0` tag) in the base starter repo. In that release the starter uses the released versions of @vaadin/connect, vaadin-connect and vaadin-connect-maven-plugin.
 - add release notes in GitHub for both the connect and the starter repos

**Comment by manolo** [comment]
I released 0.3.1 instead of 0.4.0 there were no API or breaking changes from last version that needed to increase to increase minor, see changes log https://github.com/vaadin/vaadin-connect/releases/tag/v0.3.1
