### ISSUE TITLE
read Vaadin Service project properties from a text file

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#23]
When using Vaadin Services in my app I want to customize the default configuration of my app trough a plain-text .properties file so that I can change the most common project properties without changing the source code of the app (e.g. the RPC endpoint, JWT signing key, bundling and minification settings, etc).

DoD:
 - if a `vaadin.properties` file is present in `/src/main/resources/` it is parsed at the app startup and its contents become available via an **internal** static `VaadinConnectProperties` class
 - there is a documentation page describing how to use the `vaadin.properties` file and listing well-known Vaadin Connect property names (the exact set of properties is to be defined in other tickets, one by one)

The [common DoD](https://github.com/vaadin/vaadin-services/wiki/Definition-of-Done) applies.

**Comment by SomeoneToIgnore** [comment]
Decided not to enforce `vaadin.properties` file.
Also, for simplicity, decided to go with Spring Boot support only and don't bother with getting the parameters out of system properties, web servlet properties etc.
Instead, we provide a class with getters for all the configurable properties.

Additionally, to avoid clashes of the property names, `vaadin.connect` prefix is used for each configurable property.
