### ISSUE TITLE
username / password auth should work in the API browser

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#274]
When calling a secured Vaadin Service method from the API browser I want to authenticate with username / password (not with a JWT) so that I do not have to call a cURL command to fetch an access token first, before I can call a protected method.

DoD:
 - the OpenAPI spec generator is updated to emit `oauth2 / password` security scheme instead of `bearer / jwt` for secured API endpoints. See more details in the Open API spec: https://swagger.io/docs/specification/authentication/oauth2/.
 - in order to call a secured Vaadin Connect method via SwaggerUI,  authorization is done by entering the username and password (instead of a JSON Web Token)

depends on #58
The current way to call a secured method from the API browser (before this ticket is implemented):
 - make sure the backend is running (e.g. at `http://localhost:8080`)
 - manually, with the tool of your choice, make a POST request to the `http://localhost:8080/oauth/token` URL with the following content (URL form encoded in the body of the POST request):
    ```
    curl -X POST http://localhost:8080/oauth/token \
         -H "Accept: application/json" \
         -u vaadin-connect-client:c13nts3cr3t \
         -d username=test_login \
         -d password=test_password \
         -d grant_type=password
    ```
 - find and copy the `access_token` value in the JSON response:
    ```
    {
        "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NDgyNzgwNTEsInVzZXJfbmFtZSI6InRlc3RfbG9naW4iLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwianRpIjoiNTAxNWVhOTQtYTMzZS00OTBkLWIyOGYtYmE5ODUwMzgyNDFkIiwiY2xpZW50X2lkIjoidmFhZGluLWNvbm5lY3QtY2xpZW50Iiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl19.USnFzmyFe0JYk5v_DyCrXfhkTOSk6cqOExZz1uCO_w4",
        "token_type": "bearer",
        "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJ0ZXN0X2xvZ2luIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sImF0aSI6IjUwMTVlYTk0LWEzM2UtNDkwZC1iMjhmLWJhOTg1MDM4MjQxZCIsImV4cCI6MTU1MDgyNjg1MSwiYXV0aG9yaXRpZXMiOlsiUk9MRV9VU0VSIl0sImp0aSI6IjYzOTdkOTQ4LTdhZDQtNDkwMC1hMzcwLWZjOWNiNzM2MTdkYiIsImNsaWVudF9pZCI6InZhYWRpbi1jb25uZWN0LWNsaWVudCJ9.pdXMDAkG2Ytzt8V9gkE45mZq14SoOLi0POhI0bx6orQ",
        "expires_in": 43199,
        "scope": "read write",
        "jti": "5015ea94-a33e-490d-b28f-ba985038241d"
    }
    ```
 - click on the 'Authorize' button in the API browser UI
 - paste the copied access token value (`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NDgyNzgwNTEsInVzZXJfbmFtZSI6InRlc3RfbG9naW4iLCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwianRpIjoiNTAxNWVhOTQtYTMzZS00OTBkLWIyOGYtYmE5ODUwMzgyNDFkIiwiY2xpZW50X2lkIjoidmFhZGluLWNvbm5lY3QtY2xpZW50Iiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl19.USnFzmyFe0JYk5v_DyCrXfhkTOSk6cqOExZz1uCO_w4` in this example) into authorization dialog (and press the 'Close' button to close the dialog after that)
 - call the secured method the usual way and the API browser will include the authorization header to the request automatically

**Comment by Legioth** [comment]
I'm a little reluctant to the idea of opening up request handling for multiple types of authentication in this way. On the other hand, I also see the benefit of not simplifying API browser usage.

Would it make sense to limit this functionality to development mode?
