### ISSUE TITLE
set up the vaadin-connect-demo module

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#28]
When developing the Vaadin Connect project I want to have a runnable demo app for end-to-end tests and product demos.

DoD:
 - the vaadin-connect-demo module is a runnable web app that uses Vaadin Connect (backend and frontend)
 - it's a Spring Boot app
 - if the JS code changes in /frontend/connect, a simple page reload is enough to see the changes in the running demo app (in Chrome and other browsers supporting ES modules)
 - there is an end-to-end integration test covering both frontend and backend
 - the end-to-end tests should be started from the frontend (e.g. via `npm run e2e`)

**Comment by SomeoneToIgnore** [comment]
Java part is done via #35

**Comment by manolo** [comment]
For starting server side for frontend dev or integration tests, npm can depend on https://www.npmjs.com/package/maven-cli which installs maven etc.
