### ISSUE TITLE
User types from dependencies are not generated

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-connect#305]
When making services with Vaadin Connect, I want to be able to use types from dependencies in request and response, such as beans declared in the other package, or in third-party libraries.

Currently, when a dependency type is imported and used in a Vaadin Connect service, the generated OpenAPI spec and JS do not include schema and annotations for this type.

child of #295

**Comment by vlukashov** [comment]
child of #295

**Comment by vlukashov** [comment]
There is another use case: inherited properties. When a public property of a Java bean is inherited, I still expect to have access to it from the client side. Example:

From the Java code below
```java
public abstract class AbstractEntity {

  @Id
  @GeneratedValue
  private Long id;

  public Long getId() {
    return id;
  }
}

public class Contact extends AbstractEntity {
  private String firstName;
  private String lastName;

  public String getFirstName() {
      return firstName;
  }

  public String getLastName() {
      return lastName;
  }
}
```

I expect the followign TypeScript type definitions
```typescript
export interface AbstractEntity {
  id: number;
}

export interface Contact extends AbstractEntity{
  firstName: string; 
  lastName: string; 
}
```

But currently, the inherited property is completely missing:
```typescript
export interface Contact {
  firstName: string; 
  lastName: string; 
}
```
