### ISSUE TITLE
add a `client.isLoggedIn()` API method

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#308]
When rendering a page with several web components where each one checks if the user is logged in or not, I want to have an API method `client.isLoggedIn(): Promise<boolean>` so that I can avoid the issue described below.

> In the app generated by the wizard, the intent is to show the login view if the user is not authenticated. This is checked as
>
> ```javascript
> const isAuthenticated = async () => {
>   if (client.token) {
>     return true;
>   }
>   if (localStorage.getItem("vaadin.connect.refreshToken")) {
>     await client.login();
>     return !!client.token;
>   }
> 
>   return false;
> }
> ```
>
> `isAuthenticated()` is used to see if the requested view should be rendered, or if `login-view` should be rendered instead. It is also used to decide whether `main-layout` has children or if it should just return an empty array.
>
> All fine, except that when I refresh the app after logging in, then it will see that I am authenticated (refresh token is found, client.token is undefined) so it will render the list view I am on. This list view does a server request for data, which deletes the refresh token from localStorage and sends a request for an access token. While this request is ongoing, the main navigation is rendered and this is based on the children returned for `main-view`. At this point, `main-view` has no children because there is no access token nor a refresh token. So I get no menu at all.

**Comment by platosha** [comment]
As discussed f2f with the team:

The name sounds like it’s a getter method, although it calls `login()`, which could change the state. `checkLogin` would be a bit better, other suggestions are welcome.

There are things that we think are wrong in the `login()`method itself here, and it feels like we might need to solve them too, namely:
- It returns `Promise<void>`, `Promise<AccessToken>` would be more informative.
- It might suddenly ask for credentials. We need to think about a better credentials mechanism. As we see it, the subject method is not expected to ask for credentials, so it might be impossible to implement with the current `login()` method call.
