### ISSUE TITLE
Doc: rewrite the type convertion guide to TypeScript

### ISSUE THREAD

**Issue by platosha** [vaadin/vaadin-connect#309]
The type convertion guide requires more thinking over mechanical JavaScript → TypeScript replace.

DoD:
- should make sense for developers using TypeScript in their apps.

Split from #298

Child of #295

**Comment by vlukashov** [comment]
For the types that are mostly clear, write the docs in scope of this task:
 - the primitive types
 - arrays
 - beans
 - maps

For the types that are not very clear, research and create separate tasks:
 - date
 - enums
 - generics
 - collections (if not clear)
