### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by v3rm0n** [vaadin/vaadin-connect#327]
Very interesting project. Do you plan to add support for Kotlin at some point?
I've managed to get Vaadin Connect working with Gradle by converting the Maven plugin to a Gradle script https://gist.github.com/v3rm0n/947cf04b9134e5a6b75bf6129527b108
But it looks like you are parsing VaadinService annotations from Java source so Kotlin is not supported. Have you thought about using compile time annotation processing instead? That way other JVM languages would be supported as well.

**Comment by vlukashov** [comment]
Support for Kotlin is one potential expansion area for this project. I think it would be great to add it at some point. For now, in the spirit of MVP we are focusing on a smaller set of use cases and only build support for Java.

The main reason for parsing the source code (not the byte code) is that we want to read Javadoc comments and parameter names (to use them in the generated TS code). And by default those are not available from compiled classes.

The TypeScstip generator currently works in a two-step process. First, the Java source gets parsed and an OpenAPI spec file gets created. Second, the TypeScript code is generated based on the OpenAPI spec file. Adding support for other languages than Java would require replacing only the first step of the process.

Out of curiosity, how did you come across this project? As far as I know there has not been much publicity around it yet.

**Comment by v3rm0n** [comment]
Thanks for the reply! Makes sense. I also tried to create special Java interfaces that I annotated with VaadinService and implemented in Kotlin code, which would also create this nice separation of Vaadin code from the service layer, but for some reason code generation from interfaces didn't work, didn't look into it much but couldn't find any code that would ignore interfaces...

I found it by going to https://vaadin.com/labs when I was going through Vaadin docs. I like the rapid prototyping that Vaadin enables us to do for internal apps, but I haven't found a good way to connect a React frontend to Vaadin (Lumo doesn't have enough UI elements for us), so Vaadin Connect seemed like it would help us a lot.

**Comment by macjuan** [comment]
@v3rm0n what elements are missing? Perhaps you can find them from vaadin.com/directory or from webcomponents.org.

**Comment by v3rm0n** [comment]
IMO directory isn't a good way to find elements to build a UI with. Usually I have a vague idea what I want and I browse UI docs and "see" what I need (for example like this https://blueprintjs.com/). I have no idea what the names of elements are before I see them and then find out what it is called.

Also currently we only have server side code, if we start adding frontend code it makes sense to find a mature UI framework and use components from there. Vaadin Components look mature, but there are less than 30 of them. Directory doesn't feel mature, seems like a mix of Lumo, Material and unstyled components.

**Comment by macjuan** [comment]
Maido - I am honestly asking - what components or UI elements are missing Vaadin component set?

**Comment by v3rm0n** [comment]
Toast, charts, breacrumbs, slider, popover, loader

**Comment by Firestorm87** [comment]
@v3rm0n Why do you not use OpenSpec Annotations like Swagger does, instead of the sourcecode params and java-docs?
I would like the possibility to use different parameter names between source and api.

**Comment by vlukashov** [comment]
@Firestorm87, I can see several use cases when it comes to connecting a TypeScript front-end with a JVM-based back-end, with an OpenAPI spec in between. Can you please describe the use case you have in mind?

When there are more than one front-end and / or back-end in scope, then the OpenAPI spec would likely be the 'common language'. In that case the OpenAPI spec file would likely be hand-written, while language-specific bindings would be generated. In that case it totally makes sense to separate the Java parameter names and comments from those in the OpenAPI spec.

For simple cases with a single front-end and a single back-end, the too generic approach would likely be an 'overkill'. In that case the OpenAPI spec is only an auto-generated intermediary representation, and the Java source is what defines the API. With this approach we explicitly wanted to avoid any manual editing of the Open API spec. This is the case we had in mind when building this experiment.

Could you please open up the background for your question? What use case do you have in mind?

**Comment by Firestorm87** [comment]
@vlukashov The most important use case for me is to decouple from (java) sourcecode. 
In my Mind are 2 very common scenarios where this is imortant.

1. The possibility to use other jvm languages like kotlin 
2. The possibility to use service endpoints from common maven modules without local Sourcecode. In bigger projects i have seen structures where a dedicated endpoint Module would be the preferred project structure.

**Comment by vlukashov** [comment]
Since Vaadin Connect is being integrated into Vaadin 15+, I am moving this discussion into the vaadin/flow repo: https://github.com/vaadin/flow/issues/7226.

Please fill free to continue the discussion in that issue.
