### ISSUE TITLE
TS generator does not add imports for inner classes

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#338]
When generating TypeScript wrappers with vaadin-connect-maven-plugin I expect that the generated wrappers can be compiled without errors. In the following example this is not the case:

The Java class:
```java
@VaadinService
public class ProductEndpoint {
    public static class Filter {
        private String path;
        private String value;
    }
    
    public List<Product> getPage(Set<Filter> filters) {
    }
}
```

The generated TS service module:
```typescript
// @ts-ignore
import client from './connect-client.default';
import Product from './com/vaadin/polyglotdx/data/Product';

export function getPage(
  filters: Filter[],
): Promise<Product[]> {
}
```

This does not compile because the import of the `Filter` type is missing. It should be added like `import Filter from "./com/vaadin/polyglotdx/endpoint/ProductEndpoint/Filter";`

**Comment by qtdzz** [comment]
I realized that the import will not be there if the parameter's type is a complex type (map, array). The suspicious code is here `com.vaadin.connect.plugin.generator.VaadinConnectTsGenerator#fromRequestBody`. 

When fixing this, it would be nice to also verify the similar use cases for a complex return type.
