### ISSUE TITLE
Create a new empty CCDM branch in the Flow project and make it protected with all the regular status checks

### ISSUE THREAD

**Issue by Legioth** [vaadin/vaadin-connect#417]
Should also rename the existing prototype branch to e.g. `ccdm-proto` so that we can keep using the more logical `ccdm` name for the main work.

**Comment by manolo** [comment]
Branch is there https://github.com/vaadin/flow/tree/ccdm, as well as CI  https://bender.vaadin.com/viewType.html?buildTypeId=Flow_Snapshots_FlowSnapshots30ccdm
