### ISSUE TITLE
Modify flow-client so as it can request server to initialize the UI

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-connect#419]
- When flow-client is loaded it should ask server for creating a session, ui, and get the configuration (uidl, appId, etc).
- It should configure client side with errors, stats, push and any other thing that happens in current bootstrap
- It would require changes in server side
- code should not throw errors when run in strict mode

**Comment by vlukashov** [comment]
moved to https://github.com/vaadin/flow/issues/6132
