### ISSUE TITLE
Vaadin Client should have an extention point for a user credentials provider

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#55]
When using the Vaadin Connect JS client, I want to provide a callback for it to call when it needs user credentials, so that it is able to automatically use user credentials for authentication as a fallback option if nether access token nor refresh token is available.

That allows me (as an app developer) to define either an interactive or a non-interactive interface to obtain user credentials to access the Vaadin Connect backend, and that would be the only piece of custom code I need to write to use a Vaadin Connect JS client in my app.

DoD:
 - Vaadin Client has a `credentials` constructor option that is an async callback returning a `{username: 'user-name', password: 'plain-text-password', stayLoggedIn: Boolean}` object when called.
 - the `credentials` callback is called in the following scenarios:
   - the user has initiated a backend call and Vaadin Client has neither access nor refresh token
   - the user has initiated a backend call and Vaadin Client has tried to use a refresh token and the auth server has rejected it
   - Vaadin Client has tried to use the value returned by the `credentials` callback and the auth server has not accepted the provided credentials (in this case the `credentials` callback is called with a parameter object `{message: '[message-string-returned-by-the-auth-server]'}`)
 - the `credentials` callback is NOT called when a [proactive token refresh fails](https://github.com/vaadin/vaadin-services/issues/14)
 - when the `credentials` callback (eventually) returns a truthy value, Vaadin Client uses the username and password with the `/token` endpoint to obtain a new pair of access and refresh tokens, and then (if successful) proceeds to make the original backend call
 - when the `stayLoggedIn` property returned by the `credentials` callback is false the Vaadin Client does not request / store the refresh token, and clears any existing refresh token
 - when no `callback` is defined, or the value returned by the callback is (eventually) falsey, the Vaadin Client proceeds to make the original backend call without adding an auth header

The [common DoD](https://github.com/vaadin/vaadin-services/wiki/Definition-of-Done) applies.

**Comment by manolo** [comment]
@vlukashov 
Questions:
1.- These depends on #11 but it still depends on this because there is no token implementation yet in client.js
> - the user has initiated a backend call and Vaadin Client has tried to use a refresh token and the auth server has rejected it
> - the credentials callback is NOT called when a proactive token refresh fails
> - when the credentials callback (eventually) returns a truthy value, Vaadin Client uses the username and password with the /token endpoint to obtain a new pair of access and refresh tokens, and then (if successful) proceeds to make the original backend call
> - when the stayLoggedIn property returned by the credentials callback is false the Vaadin Client does not request / store the refresh token, and clears any existing refresh token

2.- Do We loop for ever here?
> - Vaadin Client has tried to use the value returned by the credentials callback and the auth server has not accepted the provided credentials (in this case the credentials callback is called with a parameter object {message: '[message-string-returned-by-the-auth-server]'})

**Comment by vlukashov** [comment]
> 2.- Do We loop for ever here?
> > Vaadin Client has tried to use the value returned by the credentials callback and the auth server has not accepted the provided credentials (in this case the credentials callback is called with a parameter object {message: '[message-string-returned-by-the-auth-server]'})

Yes. The reasoning here is to support the typical interactive login form where users are given an infinite number of attempts to enter a correct username and password pair.

**Comment by vlukashov** [comment]
> 1.- These depends on #11 but it still depends on this because there is no token implementation yet in client.js

Could you please clarify how does this task depend on the "[Vaadin Client should automatically show a login form when access token is missing](https://github.com/vaadin/vaadin-connect/issues/11)" ticket? I think the dependency is in the opposite direction: the default login form would be the default implementation for the `credentials` callback. But when implementing the support for this callback why is there a dependency on its default value?

**Comment by manolo** [comment]
> Could you please clarify how does this task depend on the 11

**Comment by manolo** [comment]
related with looping we should stop if server response is not a 400-40x response
