### ISSUE TITLE
Include jsDoc for user-defined types 

### ISSUE THREAD

**Issue by qtdzz** [vaadin/vaadin-connect#70]
The generator should generate jsDoc for user-defined types recursively and include (or import?) them in the js services.

**Comment by SomeoneToIgnore** [comment]
This ticket is only about the Java classes' docs, not their fields' or methods' docs.

**Comment by vlukashov** [comment]
In scope:
 - OpenAPI generator changes
 - JS generator changes
 - generate all referenced JSDoc typedefes in each service wrapper
 - no support for foo.User vs bar.User types
