### ISSUE TITLE
expose the access token data to frontend code

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#78]
When using a `ConnectClient` as an auth client, I want to access the details of the currently active access token so that I do not have to explicitly fetch from the backend the data that is already included into the token (user name, roles, etc).

DoD:
 - the raw access token value is a private field of a `ConnectClient` instance and is not accessible to other code
 - the claims contained in the access token (which is a JSON Web Token) are available for frontend code as a read-only property `accessToken` on the client instance:
   ```javascript
   import client form './generated/connect-client.default.js';
   console.log(client.getToken());
   ```
   prints
   ```javascript
    {
      "jti": "cccb6266-ed96-42fd-8bb5-9c272b7c9815",
      "exp": 1543521189,
      "user_name": "test_login",
      "authorities": [
        "ROLE_USER"
      ]
    }
   ```
 - editing the returned object has no effect on the actual token, nor on the value returned when getting the `accessToken` again.

The [common DoD](https://github.com/vaadin/vaadin-services/wiki/Definition-of-Done) applies.

**Comment by manolo** [comment]
At the same time we should remove public API of `client.accessToken`
