### ISSUE TITLE
release Vaadin Connect 0.1.0

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#81]
When building a prototype with Vaadin Connect I want to depend on a specific version of Java  / JS Vaadin Connect packages so that it does not change without me knowingly updating the dependency version in my pom.xml / package.json.

DoD:
 - the `com.vaadin:vaadin-connect:0.1.0` dependency can be installed from the `maven.vaadin.com/vaadin-prereleases` repo
 - both sources and javadoc for `com.vaadin:vaadin-connect` are available on  `maven.vaadin.com/vaadin-prereleases` as well
 - the demo app is not included into the `com.vaadin:vaadin-connect` dependency. Only the core library
 - the `com.vaadin:vaadin-connect-maven-plugin:0.1.0` dependency can be installed from  the `maven.vaadin.com/vaadin-prereleases` repo
 - the `@vaadin/connect#0.1.0` package can be installed from npm
 - there is a `0.1.0` GitHub release (and a `v0.1.0` tag) in the base starter repo. In that release the starter uses the released versions of @vaadin/connect, vaadin-connect and vaadin-connect-maven-plugin.
 - add release notes in GitHub for both the connect and the starter repos
 - create a release check list
 - there is a build in bender.vaadin.com that does publishing to maven and npm

**Comment by qtdzz** [comment]
[The release checklist](https://docs.google.com/spreadsheets/d/13E1G20zgEb5PiBQH9-diPS0a8CDn5NrnfrruZegxJ0M/edit#gid=0)
