### ISSUE TITLE
Vaadin Connect starter project

### ISSUE THREAD

**Issue by vlukashov** [vaadin/vaadin-connect#9]
When I want to try out Vaadin Connect or start a new project with it, I want to have a project starter that is easy to clone, start, run tests, build and package. That way I do not have read lots of docs _before_ I can even get started, and I do not have to read docs to find out how to run a project, how to add tests, and so on.

The same project starter can be used to create integration tests for the Vaadin Connect project.

DoD:
 - there is a separate GitHub repo for a Vaadin Connect starter at https://github.com/vaadin/base-starter-connect
 - the starter has a file structure according to the [impl. proposal document](https://docs.google.com/document/d/1SP5vOK6vUuEsb4zNWjoYj0fhlBgn7QNQGnu5ujyTRvA/edit?pli=1#heading=h.afbr5iuja35b)
 - the starter has npm scripts / maven goals to start, run tests, build the project
 - the starter has a README.md describing what it is and how to start a project with it
 - the starter has the Apache 2.0 license

**Comment by Legioth** [comment]
Implementing Vaadin CLI functionality as described in the linked document is out of scope. Requiring the user to trigger individual steps using e.g. `npm` or `mvn` is good enough at this point.

**Comment by Legioth** [comment]
I think we are migrating towards new terminology for starters. The impact of this would be that the name of the repository should be `base-starter-services` instead.

**Comment by SomeoneToIgnore** [comment]
Should the name be `base-starter-connect` now?

**Comment by SomeoneToIgnore** [comment]
https://github.com/vaadin/base-starter-connect/pull/1
